### PR TITLE
Correct prebuild DPI order

### PR DESCRIPTION
**Pull request by tetsuo55**
As it turns out they want us to go from high to low resolution instead of the other way around.

### CODE REVIEW

**Comment by timduru** [comment]
that would mean mdpi at the end too

**Comment by tetsuo55** [comment]
Let me explain in more detail then.
We want only mdpi assets but when these are not available we need to find one in an incorrect DPI and scale that to mdpi.

The documentation suggested to me that upscaling seemed to be prefered but i later found more detailed documentation that says we should always prefer downscaling over upscaling.

So what we do is try to set the correct dpi, so starting with mdpi
Then we search for higher resolution assets to downscale. Due to the way google suggest things are done we are likely to find one in either xhdpi or hdpi so we search there next. Everything from there on is pretty much legacy backup for apps that have no assets for xhdpi, hdpi or mdpi.

**Comment by timduru** [comment]
the thing is that I'm not sure mdpi is high res enough on a 10.1 screen. 
It's basically the "fuzzy" effect we see on the launcher I think. 
I'll have to test to see if starting from higher res might not be better.

**Comment by tetsuo55** [comment]
Well there aren't any more dots to show on the screen. with 1:1 pixel mapping there isnt more detail in an xhdpi asset than there is in an mdpi asset. The biggest downside of using non-matching assets is that they must be scaled to the dpi setting of your screen.

So what happens is an xhdpi asset becomes an mdpi assets by realtime resizing on startup, at a possibly significant cost in performance.

Testing here again is very usefull ofcourse like it was with the dpi settings.

**Comment by timduru** [comment]
The thing is that for example with the Launcher, icons were set at 64px, 
so it was using our preferred "matching" dpi first which are 48px icons then scaling them up, generating the fuzzy issue.
For the moment what I did is to force the icon to 72px in the launcher which will now auto select the hdpi icons and not generate resizing, that will still match 1:1 for screen pixel even at 72px , because it has nothing to do with screen density, it's just the icon size, ie the launcher is asking them to be 72px in size, not 48px.

So I'm wondering what would happen if we set our default aapt pref to hdpi
and rollback the launcher workaround (ie fallback to like it was before and use a smaller 64px icons target, which look nicer in ratio/screen)
will it use 48px and scale up fuzzy like before or will it use our new preferred res of 72px and scale down.
While that might work fine for the launcher, that might also have the side effect of scaling down all the other icons from 72 if they are requested to be 48. Difficult to know.
I don't have much time to test all that currently , so I think I'll just go easy , switch back to mdpi and keep the launcher workaround for the moment.

**Comment by tetsuo55** [comment]
Yes you are right, at higher dp rendering the application, launcher in this case, should select the correct dpi for rendering at that size. this should have nothing to do with the default dpi selection we are doing here.

So for now commit this and keep the workaround.

**Pull request closed without merging**
